name: CMake

on:
  push:
    branches: [ task5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}/task5
      run: git clone https://github.com/google/googletest.git; mv googletest 3rdparty; mkdir build; cd build; cmake ..; cmake --build .
